// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPnuF_91vBJQmZfYTPJPxTCuhJ6-28odI',
    appId: '1:134281993297:web:08ff1ec04e0bcac1a4ac70',
    messagingSenderId: '134281993297',
    projectId: 'open-router-ai',
    authDomain: 'open-router-ai.firebaseapp.com',
    storageBucket: 'open-router-ai.firebasestorage.app',
    measurementId: 'G-MYEG5GNMZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKEFMUJoYR2nnpRXXIm9Mir2T_L_Xzj88',
    appId: '1:134281993297:android:707afb1bfccd7d7ba4ac70',
    messagingSenderId: '134281993297',
    projectId: 'open-router-ai',
    storageBucket: 'open-router-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCADxyGIP_Tg-l6U_YlKFY6EWjoZM3fs4k',
    appId: '1:134281993297:ios:14509a16158bd0e9a4ac70',
    messagingSenderId: '134281993297',
    projectId: 'open-router-ai',
    storageBucket: 'open-router-ai.firebasestorage.app',
    iosBundleId: 'com.example.gpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCADxyGIP_Tg-l6U_YlKFY6EWjoZM3fs4k',
    appId: '1:134281993297:ios:14509a16158bd0e9a4ac70',
    messagingSenderId: '134281993297',
    projectId: 'open-router-ai',
    storageBucket: 'open-router-ai.firebasestorage.app',
    iosBundleId: 'com.example.gpt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPnuF_91vBJQmZfYTPJPxTCuhJ6-28odI',
    appId: '1:134281993297:web:b11899cb391a8247a4ac70',
    messagingSenderId: '134281993297',
    projectId: 'open-router-ai',
    authDomain: 'open-router-ai.firebaseapp.com',
    storageBucket: 'open-router-ai.firebasestorage.app',
    measurementId: 'G-WT481B1N3C',
  );
}
